### Create Game
POST {{url}}/api/games
Content-Type: application/json

{
  "gameId": "01890f4e-93ad-7cc4-8a8f-5b2966e01468",
  "players": [
    "{{ada_public_id}}",
    "{{grace_public_id}}"
  ]
}

### Join matchmaking pool as Ada
POST {{url}}/api/matchmaking/{{pool_id}}/join
Content-Type: application/json

{
  "userId": "{{ada_public_id}}"
}

### Join matchmaking pool as Grace (creates the game)
POST {{url}}/api/matchmaking/{{pool_id}}/join
Content-Type: application/json

{
  "userId": "{{grace_public_id}}"
}

### Check Ada's match
GET {{url}}/api/matchmaking/{{pool_id}}/{{ada_public_id}}

### Check Grace's match
GET {{url}}/api/matchmaking/{{pool_id}}/{{grace_public_id}}
