CREATE TABLE users (
  id INTEGER PRIMARY KEY,
  public_id TEXT NOT NULL UNIQUE,

  name TEXT NOT NULL,

  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
